### ISSUE TITLE
Error: building Kubernetes config: invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by ahmetb** [nimakaviani/knative-inspect#5]
I'm getting error:

> Error: building Kubernetes config: invalid configuration: no configuration has been provided

I can't seem to get past behind this (using a GKE cluster). But it seems like this tool is importing the auth plugins pkg, so I can't tell what's happening.

I also specified --kubeconfig ~/.kube/config, did not work

    ./kni inspect --kubeconfig ~/.kube/config -s hello

**Comment by ahmetb** [comment]
https://github.com/nimakaviani/knative-inspect/blob/0c821a06c2867ef3f792e991f81ba5ae4cbfdfa1/pkg/cmd/core/config.go#L71-L74

I think this part is incorrect, because once I did

    export KUBECONFIG=~/.kube/config

it has worked, but this is default for almost all tools, so this should not be necessary. I guess something is missing from config loading rules above.

**Comment by nimakaviani** [comment]
should be fixed in head. will make another release by the end of the week.
