### ISSUE TITLE
show apiGroups in inspect output

### ISSUE THREAD

**Issue by ahmetb** [nimakaviani/knative-inspect#7]
A user new to knative might not know Istio. That's why by default listing KINDs with ApiGroup prefix would be awesome

For example `VirtualService.networking.istio.io` would be great, because it works like:

    kubectl get VirtualService.networking.istio.io

as well, so users won't be confused.

**Comment by nimakaviani** [comment]
I agree it is useful to show the apiGroup for each resource, but I like the less verbose version as it fits a split-window screen nicely, particularly when watching resources as they come and go during a scale up/down.

That said, I included a `--verbose` or `-v` flag to inspect, that lists apiGroups as a separate column in the table view. Let me know what you think!

**Comment by nimakaviani** [comment]
closing this as from our offline conversation it appears to work for you.
